// generated by mBlock5 for <your product>
// codes make you happy

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  pinMode(13,OUTPUT);
  while(1) {
      tone(13,440,0.25*1000);
      delay(0.25*1000);
      tone(13,440,0.25*1000);
      delay(0.25*1000);
      tone(13,659,0.25*1000);
      delay(0.25*1000);
      tone(13,698,0.25*1000);
      delay(0.25*1000);
      tone(13,698,0.25*1000);
      delay(0.25*1000);
      tone(13,659,0.5*1000);
      delay(0.5*1000);
      tone(13,587,0.25*1000);
      delay(0.25*1000);
      tone(13,587,0.25*1000);
      delay(0.25*1000);
      tone(13,698,0.25*1000);
      delay(0.25*1000);
      tone(13,698,0.25*1000);
      delay(0.25*1000);
      tone(13,659,1*1000);
      delay(1*1000);
      tone(13,587,0.25*1000);
      delay(0.25*1000);
      tone(13,587,0.25*1000);
      delay(0.25*1000);
      tone(13,698,0.25*1000);
      delay(0.25*1000);
      tone(13,698,0.25*1000);
      delay(0.25*1000);
      tone(13,659,0.25*1000);
      delay(0.25*1000);
      tone(13,587,0.25*1000);
      delay(0.25*1000);
      tone(13,523,0.5*1000);
      delay(0.5*1000);
      tone(13,494,0.25*1000);
      delay(0.25*1000);
      tone(13,494,0.25*1000);
      delay(0.25*1000);
      tone(13,523,0.25*1000);
      delay(0.25*1000);
      tone(13,494,0.25*1000);
      delay(0.25*1000);
      tone(13,440,0.5*1000);
      delay(0.5*1000);

      _loop();
  }

}

void _loop() {
}

void loop() {
  _loop();
}