// generated by mBlock5 for <your product>
// codes make you happy

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include <LCD-I2C.h>

LCD_I2C lcd(0x27, 16, 2);  // Default address of most PCF8574 modules, change according

float mesafe = 0;

float getDistance(int trig, int echo) {
  pinMode(trig, OUTPUT);
  digitalWrite(trig, LOW);
  delayMicroseconds(2);
  digitalWrite(trig, HIGH);
  delayMicroseconds(10);
  digitalWrite(trig, LOW);
  pinMode(echo, INPUT);
  return pulseIn(echo, HIGH, 30000) / 58.0;
}

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while (millis() < endTime) _loop();
}

void setup() {
  lcd.begin();
  lcd.display();
  lcd.backlight();

  Serial.begin(115200);
  while (1) {
    lcd.clear();
    mesafe = getDistance(13, 12);
    //Serial.println(mesafe);
    lcd.setCursor(0, 0);
    lcd.print(mesafe);

    delay(300);
  }
}

void _loop() {
}

void loop() {
  _loop();
}